# fly.toml app configuration file generated for cari-info on 2023-09-23T09:15:57+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cari-info"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
